import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { TourProvider } from "@/contexts/TourContext";
import { AuthErrorBoundary } from "@/components/AuthErrorBoundary";
import { SessionChecker } from "@/components/SessionChecker";
import { SessionManager } from "@/components/SessionManager";
import { FeedbackButton } from "@/components/FeedbackButton";
import TourOverlay from "@/components/TourOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap", // Usar swap para mejor performance
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap", // Usar swap para mejor performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthErrorBoundary>
          <AuthProvider>
            <TourProvider>
              {/* Validar token periódicamente en background */}
              <SessionChecker />
              {/* Gestionar timeout por inactividad con modal */}
              <SessionManager />
              {children}
              {/* Tour Overlay - Mostrar tour actual */}
              <TourOverlay />
              {/* Feedback Button - Floating action */}
              <FeedbackButton />
            </TourProvider>
          </AuthProvider>
        </AuthErrorBoundary>
      </body>
    </html>
  );
}
